load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files([
    "Cargo.toml",
], visibility = ["//visibility:public"])

rust_library(
    name = "lease_heartbeat",
    crate_name = "lease_heartbeat",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    aliases = aliases(),
    deps = [
        "//crates/config:config",
        "//crates/process:process",
        "//crates/storage:storage",
        "//crates/workflow:workflow",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "tests",
    crate = ":lease_heartbeat",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    visibility = ["//visibility:public"],
)
