//! Canonical wire states shared by the IM core, scenario adapters and clients.
//! Preserve serialized values: existing journals and API clients depend on them.
use serde::{Deserialize, Serialize};

macro_rules! states {
    ($($(#[$enum_meta:meta])* $name:ident { $($(#[$variant_meta:meta])* $variant:ident => $wire:literal),+ $(,)? })+) => {
        $(
            #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
            $(#[$enum_meta])*
            pub enum $name { $($(#[$variant_meta])* #[serde(rename = $wire)] $variant),+ }
            impl $name {
                pub const ALL: &'static [Self] = &[$(Self::$variant),+];
                pub const fn as_str(self) -> &'static str {
                    match self { $(Self::$variant => $wire),+ }
                }
                pub const fn code(self) -> &'static str { self.as_str() }
                pub fn parse(value: &str) -> serde_json::Result<Self> {
                    serde_json::from_value(serde_json::Value::String(value.into()))
                }
                /// Unknown external states remain unknown; they never imply success.
                pub fn from_value(value: &serde_json::Value) -> Option<Self> {
                    value.as_str().and_then(|s| Self::parse(s).ok())
                }
            }
            impl std::fmt::Display for $name {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    f.write_str(self.as_str())
                }
            }
        )+
        /// Generate executable constants and their associated TypeScript union types.
        pub fn typescript() -> String {
            let mut out = String::from("// Generated by //crates/contracts:generate. Do not edit.\n");
            $(
                out.push_str(concat!("export const ", stringify!($name), " = {\n"));
                $(out.push_str(concat!("  ", stringify!($variant), ": \"", $wire, "\",\n"));)+
                out.push_str(concat!("} as const;\nexport type ", stringify!($name), " = (typeof ", stringify!($name), ")[keyof typeof ", stringify!($name), "];\n"));
            )+
            out
        }
        pub fn catalog() -> serde_json::Value {
            let mut values = serde_json::Map::new();
            $(values.insert(stringify!($name).into(), serde_json::json!($name::ALL));)+
            serde_json::Value::Object(values)
        }
    }
}

states! {
    ServiceKind { Storage => "storage", Executor => "executor", Sandbox => "sandbox" }
    ServiceHealth { Healthy => "healthy", Unavailable => "unavailable", Disabled => "disabled", ProtocolMismatch => "protocol_mismatch", RestartRequired => "restart_required" }
    CodingAgent { ClaudeCode => "cc", Codex => "codex", DeepseekHarness => "hds", Pi => "pi", Custom => "custom" }
    AgentProtocol { JsonStdioV1 => "json_stdio_v1" }
    OriginStateKind { Active => "active", Completed => "completed", Revoked => "revoked" }
    Presence { Offline => "offline", Online => "online", Chatting => "chatting", Busy => "busy" }
    #[derive(Default)]
    GroupKind { #[default] Conversation => "conversation", Temporary => "temporary", Board => "board" }
    PersonKind { Fixed => "fixed", Temporary => "temporary", Research => "research" }
    GoalState { Active => "active", Completed => "completed", Cancelled => "cancelled" }
    WorkState { Ready => "ready", Running => "running", Submitted => "submitted", Failed => "failed" }
    ExecutionState {
        Ready => "ready", Running => "running", Succeeded => "succeeded", Failed => "failed",
        Blocked => "blocked", Unknown => "unknown", Paused => "paused", RetryWait => "retry_wait",
        NeedsReconciliation => "needs_reconciliation", WaitingDependencies => "waiting_dependencies",
        WaitingTarget => "waiting_target", Historical => "historical"
    }
    WorkflowState { Running => "running", Succeeded => "succeeded", Failed => "failed", Cancelled => "cancelled", Unknown => "unknown" }
    WorkflowNodeState { TaskReady => "task_ready" }
    EffectState { Applied => "applied", Unknown => "unknown" }
    ControllerPhase { Unknown => "unknown", Idle => "idle", Running => "running", Error => "error", Stopped => "stopped", Starting => "starting", Recovering => "recovering", Refreshing => "refreshing" }
    MemoryWriteback { Pending => "pending", Running => "running", Done => "done", Unknown => "unknown", NotEnabled => "not_enabled" }
    FollowupAdmission { Pending => "pending", Running => "running", Done => "done", Blocked => "blocked" }
    FollowupState { DeferredTaskScope => "deferred_task_scope", DeferredBudget => "deferred_budget", FollowupBlocked => "followup_blocked" }
    QueueState { Pending => "pending", Running => "running", Complete => "complete", Waiting => "waiting", NeedsReconciliation => "needs_reconciliation" }
    DeliveryState { Delivered => "delivered", Expired => "expired", Pending => "pending" }
    ExperimentTaskState { NotEnqueued => "not_enqueued", InvalidBinding => "invalid_binding", Succeeded => "succeeded", InvalidReport => "invalid_report" }
    ProposalState { PendingHostReview => "pending_host_review" }
    GoalEventKind { Created => "goal_created", Accepted => "goal_accepted", Cancelled => "goal_cancelled", Retried => "work_retried", Claimed => "work_claimed", Submitted => "work_submitted", Failed => "work_failed" }
    ScenarioStatus { Ready => "scenario_ready", Unavailable => "scenario_unavailable", BatchComplete => "scenario_batch_complete" }
    ApiNotice { BoundPolicyUnavailable => "bound_policy_unavailable", BoundPolicyScope => "bound_policy_scope", LineageUnavailable => "lineage_unavailable", SnapshotReadFailed => "snapshot_read_failed", ObserverOverflow => "observer_overflow", ObserverInterrupted => "observer_interrupted", PublicEventScope => "public_event_scope", WorkflowObservationIncomplete => "workflow_observation_incomplete", BoardUnavailable => "board_unavailable", SnapshotLoading => "snapshot_loading", ObserverUnavailable => "observer_unavailable", MemoryScope => "memory_scope", DirectoryLimit => "directory_limit", JobLimit => "job_limit", JobUnavailable => "job_unavailable", BoardLimit => "board_limit", GroupUnavailable => "group_unavailable" }
    SessionItemStatus { InProgress => "in_progress", Completed => "completed", Failed => "failed", Error => "error", Unknown => "unknown" }
    SessionEventKind { SessionStarted => "session_started", TurnStarted => "turn_started", TurnCompleted => "turn_completed", ExecutionError => "execution_error", ToolStarted => "tool_started", ToolCompleted => "tool_completed", AgentMessage => "agent_message", FileChange => "file_change", Activity => "activity" }
    WorkResultCode { ExecutorFailed => "executor_failed", Completed => "research_completed", Failed => "research_failed", AdmissionFailed => "research_admission_failed" }
}
impl Presence {
    pub fn receives(self) -> bool {
        matches!(self, Self::Online | Self::Chatting)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "state", rename_all = "snake_case", deny_unknown_fields)]
pub enum OriginState {
    Active,
    Completed { receipt_sha256: String },
    Revoked { reason: String },
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn wire_values_roundtrip_and_reject_unknown_states() {
        for state in ExecutionState::ALL {
            assert_eq!(ExecutionState::parse(state.as_str()).unwrap(), *state);
            assert_eq!(serde_json::to_value(state).unwrap(), state.as_str());
        }
        assert!(WorkflowState::from_value(&serde_json::json!("future_state")).is_none());
        assert!(GoalState::parse("succeeded").is_err());
        assert_eq!(Presence::parse("busy").unwrap(), Presence::Busy);
        assert_eq!(
            serde_json::to_value(OriginState::Completed {
                receipt_sha256: "abc".into()
            })
            .unwrap(),
            serde_json::json!({"state":"completed","receipt_sha256":"abc"})
        );
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Notice {
    pub code: ApiNotice,
    pub parameters: serde_json::Value,
}
impl ApiNotice {
    pub fn notice(self, parameters: serde_json::Value) -> Notice {
        Notice {
            code: self,
            parameters,
        }
    }
}
