// Generated by //crates/contracts:generate. Do not edit.
export const ServiceKind = {
  Storage: "storage",
  Executor: "executor",
  Sandbox: "sandbox",
} as const;
export type ServiceKind = (typeof ServiceKind)[keyof typeof ServiceKind];
export const ServiceHealth = {
  Healthy: "healthy",
  Unavailable: "unavailable",
  Disabled: "disabled",
  ProtocolMismatch: "protocol_mismatch",
  RestartRequired: "restart_required",
} as const;
export type ServiceHealth = (typeof ServiceHealth)[keyof typeof ServiceHealth];
export const CodingAgent = {
  ClaudeCode: "cc",
  Codex: "codex",
  DeepseekHarness: "hds",
  Pi: "pi",
  Custom: "custom",
} as const;
export type CodingAgent = (typeof CodingAgent)[keyof typeof CodingAgent];
export const AgentProtocol = {
  JsonStdioV1: "json_stdio_v1",
} as const;
export type AgentProtocol = (typeof AgentProtocol)[keyof typeof AgentProtocol];
export const OriginStateKind = {
  Active: "active",
  Completed: "completed",
  Revoked: "revoked",
} as const;
export type OriginStateKind = (typeof OriginStateKind)[keyof typeof OriginStateKind];
export const Presence = {
  Offline: "offline",
  Online: "online",
  Chatting: "chatting",
  Busy: "busy",
} as const;
export type Presence = (typeof Presence)[keyof typeof Presence];
export const GroupKind = {
  Conversation: "conversation",
  Temporary: "temporary",
  Board: "board",
} as const;
export type GroupKind = (typeof GroupKind)[keyof typeof GroupKind];
export const PersonKind = {
  Fixed: "fixed",
  Temporary: "temporary",
  Research: "research",
} as const;
export type PersonKind = (typeof PersonKind)[keyof typeof PersonKind];
export const GoalState = {
  Active: "active",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type GoalState = (typeof GoalState)[keyof typeof GoalState];
export const WorkState = {
  Ready: "ready",
  Running: "running",
  Submitted: "submitted",
  Failed: "failed",
} as const;
export type WorkState = (typeof WorkState)[keyof typeof WorkState];
export const ExecutionState = {
  Ready: "ready",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Blocked: "blocked",
  Unknown: "unknown",
  Paused: "paused",
  RetryWait: "retry_wait",
  NeedsReconciliation: "needs_reconciliation",
  WaitingDependencies: "waiting_dependencies",
  WaitingTarget: "waiting_target",
  Historical: "historical",
} as const;
export type ExecutionState = (typeof ExecutionState)[keyof typeof ExecutionState];
export const WorkflowState = {
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Cancelled: "cancelled",
  Unknown: "unknown",
} as const;
export type WorkflowState = (typeof WorkflowState)[keyof typeof WorkflowState];
export const WorkflowNodeState = {
  TaskReady: "task_ready",
} as const;
export type WorkflowNodeState = (typeof WorkflowNodeState)[keyof typeof WorkflowNodeState];
export const EffectState = {
  Applied: "applied",
  Unknown: "unknown",
} as const;
export type EffectState = (typeof EffectState)[keyof typeof EffectState];
export const ControllerPhase = {
  Unknown: "unknown",
  Idle: "idle",
  Running: "running",
  Error: "error",
  Stopped: "stopped",
  Starting: "starting",
  Recovering: "recovering",
  Refreshing: "refreshing",
} as const;
export type ControllerPhase = (typeof ControllerPhase)[keyof typeof ControllerPhase];
export const MemoryWriteback = {
  Pending: "pending",
  Running: "running",
  Done: "done",
  Unknown: "unknown",
  NotEnabled: "not_enabled",
} as const;
export type MemoryWriteback = (typeof MemoryWriteback)[keyof typeof MemoryWriteback];
export const FollowupAdmission = {
  Pending: "pending",
  Running: "running",
  Done: "done",
  Blocked: "blocked",
} as const;
export type FollowupAdmission = (typeof FollowupAdmission)[keyof typeof FollowupAdmission];
export const FollowupState = {
  DeferredTaskScope: "deferred_task_scope",
  DeferredBudget: "deferred_budget",
  FollowupBlocked: "followup_blocked",
} as const;
export type FollowupState = (typeof FollowupState)[keyof typeof FollowupState];
export const QueueState = {
  Pending: "pending",
  Running: "running",
  Complete: "complete",
  Waiting: "waiting",
  NeedsReconciliation: "needs_reconciliation",
} as const;
export type QueueState = (typeof QueueState)[keyof typeof QueueState];
export const DeliveryState = {
  Delivered: "delivered",
  Expired: "expired",
  Pending: "pending",
} as const;
export type DeliveryState = (typeof DeliveryState)[keyof typeof DeliveryState];
export const ExperimentTaskState = {
  NotEnqueued: "not_enqueued",
  InvalidBinding: "invalid_binding",
  Succeeded: "succeeded",
  InvalidReport: "invalid_report",
} as const;
export type ExperimentTaskState = (typeof ExperimentTaskState)[keyof typeof ExperimentTaskState];
export const ProposalState = {
  PendingHostReview: "pending_host_review",
} as const;
export type ProposalState = (typeof ProposalState)[keyof typeof ProposalState];
export const GoalEventKind = {
  Created: "goal_created",
  Accepted: "goal_accepted",
  Cancelled: "goal_cancelled",
  Retried: "work_retried",
  Claimed: "work_claimed",
  Submitted: "work_submitted",
  Failed: "work_failed",
} as const;
export type GoalEventKind = (typeof GoalEventKind)[keyof typeof GoalEventKind];
export const ScenarioStatus = {
  Ready: "scenario_ready",
  Unavailable: "scenario_unavailable",
  BatchComplete: "scenario_batch_complete",
} as const;
export type ScenarioStatus = (typeof ScenarioStatus)[keyof typeof ScenarioStatus];
export const ApiNotice = {
  BoundPolicyUnavailable: "bound_policy_unavailable",
  BoundPolicyScope: "bound_policy_scope",
  LineageUnavailable: "lineage_unavailable",
  SnapshotReadFailed: "snapshot_read_failed",
  ObserverOverflow: "observer_overflow",
  ObserverInterrupted: "observer_interrupted",
  PublicEventScope: "public_event_scope",
  WorkflowObservationIncomplete: "workflow_observation_incomplete",
  BoardUnavailable: "board_unavailable",
  SnapshotLoading: "snapshot_loading",
  ObserverUnavailable: "observer_unavailable",
  MemoryScope: "memory_scope",
  DirectoryLimit: "directory_limit",
  JobLimit: "job_limit",
  JobUnavailable: "job_unavailable",
  BoardLimit: "board_limit",
  GroupUnavailable: "group_unavailable",
} as const;
export type ApiNotice = (typeof ApiNotice)[keyof typeof ApiNotice];
export const SessionItemStatus = {
  InProgress: "in_progress",
  Completed: "completed",
  Failed: "failed",
  Error: "error",
  Unknown: "unknown",
} as const;
export type SessionItemStatus = (typeof SessionItemStatus)[keyof typeof SessionItemStatus];
export const SessionEventKind = {
  SessionStarted: "session_started",
  TurnStarted: "turn_started",
  TurnCompleted: "turn_completed",
  ExecutionError: "execution_error",
  ToolStarted: "tool_started",
  ToolCompleted: "tool_completed",
  AgentMessage: "agent_message",
  FileChange: "file_change",
  Activity: "activity",
} as const;
export type SessionEventKind = (typeof SessionEventKind)[keyof typeof SessionEventKind];
export const WorkResultCode = {
  ExecutorFailed: "executor_failed",
  Completed: "research_completed",
  Failed: "research_failed",
  AdmissionFailed: "research_admission_failed",
} as const;
export type WorkResultCode = (typeof WorkResultCode)[keyof typeof WorkResultCode];
