[package]
name = "lab-knowledge"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "knowledge"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
delivery.workspace = true
process.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
