[package]
name = "ai-im"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "im_service"

[[bin]]
name = "ai-im"
path = "src/main.rs"

[dependencies]
service_protocol.workspace = true
service_api.workspace = true
im_storage.workspace = true
web_assets.workspace = true
contracts.workspace = true
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
clap.workspace = true
crystal.workspace = true
serde.workspace = true
serde_json.workspace = true
storage.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
